name: geraisdm
description: Aplikasi ini merupakan pelayanan terpadu dibidang Sumber Daya
  Manusia secara digital yang dapat diakses oleh Anggota Polri dan PNS Polri
  Polda Sumsel seta masyarakat provinsi Sumatera Selatan untuk informasi seputar
  penerimaan Anggota Polri.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  alice: ^0.2.4
  another_flushbar: ^1.10.26
  auto_route: ^3.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  catcher: ^0.6.9
  connectivity_plus: ^2.1.0
  copy_with_extension: ^2.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.1.1
  dio_cache_interceptor: ^3.0.3
  dio_cache_interceptor_hive_store: ^3.0.1
  dio_firebase_performance: ^0.3.1-dev.3
  dio_http: ^5.0.4
  drift: ^1.0.1
  easy_localization: ^3.0.0
  easy_localization_loader:
    git:
      url: git://github.com/sribuu/easy_localization_loader.git
      ref: feature/network-loader
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
  envify: ^2.0.2
  equatable: ^2.0.3
  firebase_analytics: ^9.0.3
  firebase_crashlytics: ^2.4.3
  firebase_dynamic_links: ^4.0.3
  firebase_messaging: ^11.2.3
  firebase_remote_config: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_local_notifications: ^9.2.0
  flutter_markdown: ^0.6.8
  fluttertoast: ^8.0.8
  form_field_validator: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.0.0
  image_picker: ^0.8.4+4
  in_app_review: ^2.0.3
  infinite_scroll_pagination: ^3.1.0
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  mockito: ^5.0.15
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.7
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.3
  share: ^2.0.4
  share_plus: ^3.0.4
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  showcaseview: ^1.1.4
  timezone: ^0.8.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17

dev_dependencies:
  auto_route_generator: ^3.1.0
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  copy_with_extension_gen: ^2.0.3
  drift_dev: ^1.0.2
  envify_generator: ^2.0.2
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.9.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.1
  sqlparser: ^0.18.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.prod
    - .env.dev
    - assets/localization/
    - assets/images/
    - assets/images/icon/
    - assets/images/illustration/
    - assets/images/wallet/
    - assets/images/flag/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icon/logo_trans.png

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon/logo_padding.png"
  image_path_ios: "assets/images/icon/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon/logo_trans_padding.png"

flutter_gen:
  output: lib/constant/
